/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline': '#737688',
        'surface-container-high': '#e7e8e9',
        'secondary-fixed': '#6ffbbe',
        'surface-container-low': '#f3f4f5',
        'surface-tint': '#004ced',
        'primary-fixed-dim': '#b7c4ff',
        'on-background': '#191c1d',
        'secondary': '#006c49',
        'inverse-surface': '#2e3132',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#005236',
        'outline-variant': '#c3c5d9',
        'surface-container-highest': '#e1e3e4',
        'tertiary-fixed': '#ffdad7',
        'on-primary-fixed-variant': '#0038b6',
        'error-container': '#ffdad6',
        'on-primary-container': '#dfe3ff',
        'surface': '#f8f9fa',
        'inverse-primary': '#b7c4ff',
        'on-surface-variant': '#434656',
        'secondary-container': '#6cf8bb',
        'on-secondary-fixed': '#002113',
        'tertiary': '#a10016',
        'surface-variant': '#e1e3e4',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00714d',
        'error': '#ba1a1a',
        'tertiary-container': '#c5242b',
        'background': '#f8f9fa',
        'secondary-fixed-dim': '#4edea3',
        'surface-dim': '#d9dadb',
        'on-primary-fixed': '#001452',
        'on-tertiary-fixed': '#410004',
        'primary-container': '#0052ff',
        'surface-container': '#edeeef',
        'surface-bright': '#f8f9fa',
        'on-surface': '#191c1d',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#dde1ff',
        'on-tertiary-fixed-variant': '#930013',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#ffddda',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-primary': '#ffffff',
        'primary': '#003ec7',
        'inverse-on-surface': '#f0f1f2',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        sans: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
